//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EyeTrackingMouse.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class OverlaySettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static OverlaySettings defaultInstance = ((OverlaySettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new OverlaySettings())));
        
        public static OverlaySettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsSimpleCrosshair {
            get {
                return ((bool)(this["IsSimpleCrosshair"]));
            }
            set {
                this["IsSimpleCrosshair"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsCrosshairVisible {
            get {
                return ((bool)(this["IsCrosshairVisible"]));
            }
            set {
                this["IsCrosshairVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoHideGrid {
            get {
                return ((bool)(this["AutoHideGrid"]));
            }
            set {
                this["AutoHideGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int VerticalScrollIndicatorPosition {
            get {
                return ((int)(this["VerticalScrollIndicatorPosition"]));
            }
            set {
                this["VerticalScrollIndicatorPosition"] = value;
            }
        }
    }
}
