//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EyeTrackingMouse.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class SudokuGridSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static SudokuGridSettings defaultInstance = ((SudokuGridSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SudokuGridSettings())));
        
        public static SudokuGridSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float StrokeSize {
            get {
                return ((float)(this["StrokeSize"]));
            }
            set {
                this["StrokeSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public float SecondaryStrokeSize {
            get {
                return ((float)(this["SecondaryStrokeSize"]));
            }
            set {
                this["SecondaryStrokeSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int FontSize {
            get {
                return ((int)(this["FontSize"]));
            }
            set {
                this["FontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32")]
        public int NumberOfColumns {
            get {
                return ((int)(this["NumberOfColumns"]));
            }
            set {
                this["NumberOfColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int NumberOfRows {
            get {
                return ((int)(this["NumberOfRows"]));
            }
            set {
                this["NumberOfRows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.18")]
        public float BackgroundOpacity {
            get {
                return ((float)(this["BackgroundOpacity"]));
            }
            set {
                this["BackgroundOpacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.6")]
        public float TextOpacity {
            get {
                return ((float)(this["TextOpacity"]));
            }
            set {
                this["TextOpacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.4")]
        public float StrokeOpacity {
            get {
                return ((float)(this["StrokeOpacity"]));
            }
            set {
                this["StrokeOpacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.2")]
        public float SecondaryStrokeOpacity {
            get {
                return ((float)(this["SecondaryStrokeOpacity"]));
            }
            set {
                this["SecondaryStrokeOpacity"] = value;
            }
        }
    }
}
